language: node_js

node_js:
- '0.6'
- '0.8'
- '0.12'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'

cache:
  directories:
  - $HOME/.nvm

install: true

script:
- node ./index.js -gt 0.1
- node ./index.js -lt 100000000
- npm test

deploy:
  provider: npm
  email: m@rkis.cc
  api_key:
    secure: wX7iFRlyQzg0XFH6QfKshUkjguMrqp6QTNZbvPc4TMiW/5vL77k9Kq3FgCqL2comgDdkHjL6b4Pz+svwvKBFTlsrkT27FR2rPH1u7e5LcvSU+iRMZWcgePmDbqF83GOzm9NT73T5n078KeF63MlQwqH6OlBWtYR2HOYjJcNH4Ulc+XVJz45nlsNu2AtMZU6jyLTTkkn6NHOm8YBKhoOxTBEs+EBmAyckCLOcRzRJj8o/SAFdCCAuxU983bECemkGF9up/jyHg/daVJnptkXcEjzLEA1sPehVmlTW5jmHMQ1sM6zW4aNRNe31CdGb3VdTd0LDjex9WNthUD7RVXPYLb1SA3ua5D/kZIKoymM2JKHAfMRiQoGH8mJdeBjd2Z6WM+yuTeHp7f5lQ3W9exTietQI87WZNyAkwp7kpXYektVLons5pBem2tNiGYTef+1mBeNGYz7gJbSNR6C/TrThpCj8SsMLfvbS/eqp4cY4hX+KPieIvJS+rUXj51ZyJLibVGFtco+55+ZP5qHQAlkFigRAb+zXPEpe6acMlfw4EE+qD7lJrJ1Bq7wiI+so87LLkzOyYpk0+xW173UqLErkkxzEIxPn04xyoEUh+T/NDg3/Z5QfbcONiH+O0e8uXymjo/ULH3sjdYlQIWNgL2cdOmDQJ6FXooXAwjD0E6k6xeY=
  on:
    tags: true
    repo: markis/if-ver
