name: lint 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Setup node 
      uses: actions/setup-node@v1
      with:
        node-version: 16 
    - run: npm install -g eslint@^8.5.0 prettier@^2.5.0
    - run: npm run lint
